name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn test
        env:
          CI: true
